"""
P_tab41_gate1.py
=================
Table 4.1 — Gate G1 summary.

Reads:  results/gates/gate1_results.parquet
        results/gates/chi_estimates_raw.parquet
Writes: paper/tables/tab41_gate1.tex
"""

from __future__ import annotations
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from src import config as cfg

ROOT  = Path(__file__).parent
G1_PQ = cfg.DIRS["gates"] / "gate1_results.parquet"
CH_PQ = cfg.DIRS["gates"] / "chi_estimates_raw.parquet"
OUT   = ROOT / "paper" / "tables" / "tab41_gate1.tex"
OUT.parent.mkdir(parents=True, exist_ok=True)

g1   = pd.read_parquet(G1_PQ)
chi  = pd.read_parquet(CH_PQ)

g1["dist_km"] = g1["dist_ij_m"] / 1000.0
chi["dist_km"] = chi["dist_ij_m"] / 1000.0

g1_95  = g1[g1["u"] == 0.95].copy()
chi_95 = chi[chi["u"] == 0.95].copy()
close  = g1_95[g1_95["dist_km"] < 5]

n_all    = len(g1_95)
n_close  = len(close)
n_sig    = (close["significant"] == True).sum()
frac_sig = n_sig / n_close

chi_med  = close["chi_hat"].median()
chi_q25  = close["chi_hat"].quantile(0.25)
chi_q75  = close["chi_hat"].quantile(0.75)

rows = [
    ("Total pairs analysed",             f"{n_all:,}"),
    ("Pairs with $d_{ij} \\leq 5$ km",   f"{n_close:,}"),
    ("Quantile threshold $u$",           "0.95"),
    ("Significance test",                "Block-permutation + BH ($\\alpha=0.05$)"),
    ("Significant pairs ($<$5 km)",      f"{n_sig:,} ({frac_sig:.1%})"),
    ("Gate G1 criterion",                "$\\geq 30\\%$ significant"),
    ("Gate G1 decision",                 "\\textbf{PASSED}"),
    ("Median $\\hat{\\chi}$ ($<$5 km)",  f"{chi_med:.3f} [IQR {chi_q25:.3f}--{chi_q75:.3f}]"),
]

lines = []
lines.append("% Auto-generated by P_tab41_gate1.py — do not edit manually")
lines.append("\\begin{tabular}{@{}ll@{}}")
lines.append("\\toprule")
lines.append("Metric & Value \\\\")
lines.append("\\midrule")
for label, val in rows:
    lines.append(f"{label} & {val} \\\\")
lines.append("\\botrule")
lines.append("\\end{tabular}")

OUT.write_text("\n".join(lines))
print(f"[OK] Tab 4.1 saved → {OUT}")
print(f"  n_all={n_all}, n_close={n_close}, n_sig={n_sig} ({frac_sig:.1%}), chi_med={chi_med:.3f}")
