"""
P_tab43_return_levels.py
=========================
Table 4.3 — Return levels by scenario and return period.

Reads:  results/gates/f8_rq3_ratio.parquet
        results/gates/f8b_rq3b_ratio.parquet
Writes: paper/tables/tab43_return_levels.tex
"""

from __future__ import annotations
import sys
from pathlib import Path

import pandas as pd
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from src import config as cfg

ROOT  = Path(__file__).parent
F8    = cfg.DIRS["gates"] / "f8_rq3_ratio.parquet"
F8B   = cfg.DIRS["gates"] / "f8b_rq3b_ratio.parquet"
OUT   = ROOT / "paper" / "tables" / "tab43_return_levels.tex"
OUT.parent.mkdir(parents=True, exist_ok=True)

f8  = pd.read_parquet(F8)
f8b = pd.read_parquet(F8B)

# Merge on return_period_years
df = f8.merge(f8b, on=["return_period_years", "z_real", "z_independence",
                        "z_model_implied", "ratio_real_over_independence"],
              how="inner", suffixes=("", "_b"))

T_select = [1/12, 0.25, 0.5, 1.0, 2.0]
# Select nearest available T for each target
df_sel_rows = []
for t in T_select:
    idx = (df["return_period_years"] - t).abs().argmin()
    df_sel_rows.append(df.iloc[idx])
df_sel = pd.DataFrame(df_sel_rows).reset_index(drop=True)

T_labels = {1/12: "1/12", 0.25: "1/4", 0.5: "1/2", 1.0: "1", 2.0: "2"}

lines = []
lines.append("% Auto-generated by P_tab43_return_levels.py — do not edit manually")
lines.append("\\begin{tabular}{@{}lccccc@{}}")
lines.append("\\toprule")
lines.append("Scenario & $T=1/12$ & $T=1/4$ & $T=1/2$ & $T=1$ & $T=2$ yr \\\\")
lines.append("\\midrule")

SCEN = [
    ("Real (observed)",                    "z_real"),
    ("Model-implied (H-T + Stage~1)",      "z_model_implied"),
    ("Gaussian copula (+ Stage~1)",        "z_copula_gaussian"),
    ("Closed-form (no coincidence)",       "z_closed_form_gaussian"),
    ("Independence",                       "z_independence"),
]

for label, col in SCEN:
    vals = []
    for _, row in df_sel.sort_values("return_period_years").iterrows():
        if col in row:
            vals.append(f"{row[col]:.3f}")
        else:
            vals.append("---")
    lines.append(f"{label} & " + " & ".join(vals) + " \\\\")

lines.append("\\midrule")

# Ratio rows
lines.append("\\multicolumn{6}{@{}l}{\\textit{Ratios (relative to independence)}} \\\\")
ratio_row_real = []
ratio_row_clsd = []
for _, row in df_sel.sort_values("return_period_years").iterrows():
    r_real = row["z_real"] / row["z_independence"]
    ratio_row_real.append(f"{r_real:.2f}")
    r_clsd = row["z_real"] / row["z_closed_form_gaussian"]
    ratio_row_clsd.append(f"{r_clsd:.2f}")

lines.append("Real / Independence & " + " & ".join(ratio_row_real) + " \\\\")
lines.append("Real / Closed-form  & " + " & ".join(ratio_row_clsd) + " \\\\")

lines.append("\\botrule")
lines.append("\\end{tabular}")

OUT.write_text("\n".join(lines))
print(f"[OK] Tab 4.3 saved → {OUT}")

# Quick sanity print
for _, row in df_sel.sort_values("return_period_years").iterrows():
    T = row["return_period_years"]
    print(f"  T={T:.4f}: real={row['z_real']:.3f}, ind={row['z_independence']:.3f}, "
          f"ratio={row['z_real']/row['z_independence']:.3f}")
