"""
P_tab42_model_params.py
========================
Table 4.2 — Two-stage model parameters (Stage 1 + Stage 2 + Gate G3).

Reads:  results/gates/f5_stage2_params.parquet
Writes: paper/tables/tab42_model_params.tex
"""

from __future__ import annotations
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from src import config as cfg

ROOT  = Path(__file__).parent
P2_PQ = cfg.DIRS["gates"] / "f5_stage2_params.parquet"
OUT   = ROOT / "paper" / "tables" / "tab42_model_params.tex"
OUT.parent.mkdir(parents=True, exist_ok=True)

p2 = pd.read_parquet(P2_PQ).iloc[0]

# Stage 1 parameters (from FINDINGS.md — stored as constants)
STAGE1 = [
    ("$\\hat{\\gamma}_0$ (intercept)",        "3.68",   "---",    "---"),
    ("$\\hat{\\gamma}_d$ (log distance)",     "$-$0.651", "---",  "---"),
    ("$\\hat{\\gamma}_x$ (cond. magnitude)", "$-$0.139", "---",  "---"),
    ("Pseudo-$R^2$",                          "0.93",   "---",    "---"),
    ("Matched event pairs",                   f"{int(p2['n_matched']):,}", "---", "---"),
]

# Stage 2 parameters (from parquet)
alpha0    = float(p2["alpha0"])
alpha0_lo = float(p2["alpha0_ci_low"])
alpha0_hi = float(p2["alpha0_ci_high"])
L_km      = float(p2["decay_param"])
L_lo      = float(p2["decay_ci_low"])
L_hi      = float(p2["decay_ci_high"])
beta      = float(p2["beta"])
beta_lo   = float(p2["beta_ci_low"])
beta_hi   = float(p2["beta_ci_high"])
aic_exp   = float(p2["aic_exp"])
aic_pow   = float(p2["aic_pow"])
n_boot    = int(p2["n_bootstrap_converged"])

STAGE2 = [
    ("$\\hat{\\alpha}_0$",         f"{alpha0:.3f}",
     f"[{alpha0_lo:.3f}, {alpha0_hi:.3f}]",
     "Cluster bootstrap $B=150$"),
    ("$\\hat{L}$ (decay scale, km)", f"{L_km:.2f}",
     f"[{L_lo:.2f}, {L_hi:.2f}]",
     "AIC: exp vs. power-law"),
    ("$\\hat{\\beta}$",            f"{beta:.3f}",
     f"[{beta_lo:.3f}, {beta_hi:.3f}]",
     ""),
    ("AIC exp. decay",             f"{aic_exp:.1f}", "---", ""),
    ("AIC power-law",              f"{aic_pow:.1f}", "---", "exp selected"),
    ("Bootstrap converged",        f"{n_boot}/150", "---", ""),
    ("Gate G3 ($\\rho_S$: $\\hat{\\alpha}$ vs $\\hat{\\chi}$)",
     "0.32", "---", "Passed ($>0$, coherent with G1)"),
]

lines = []
lines.append("% Auto-generated by P_tab42_model_params.py — do not edit manually")
lines.append("\\begin{tabular}{@{}lllp{4.5cm}@{}}")
lines.append("\\toprule")
lines.append("Parameter & Estimate & 95\\% CI & Note \\\\")
lines.append("\\midrule")
lines.append("\\multicolumn{4}{@{}l}{\\textit{Stage 1: excess coincidence (logistic regression with Poisson offset)}} \\\\")
lines.append("\\midrule")
for lab, est, ci, note in STAGE1:
    lines.append(f"{lab} & {est} & {ci} & {note} \\\\")
lines.append("\\midrule")
lines.append("\\multicolumn{4}{@{}l}{\\textit{Stage 2: conditional magnitude (Heffernan--Tawn, exponential decay)}} \\\\")
lines.append("\\midrule")
for lab, est, ci, note in STAGE2:
    lines.append(f"{lab} & {est} & {ci} & {note} \\\\")
lines.append("\\botrule")
lines.append("\\end{tabular}")

OUT.write_text("\n".join(lines))
print(f"[OK] Tab 4.2 saved → {OUT}")
