"""
P_tabA2_gpd_params.py
======================
Table A.2 — GPD parameters: selected stations summary (Gate G2).

Reads:  results/gates/gpd_marginal_params.parquet
Writes: paper/tables/tabA2_gpd_params.tex
"""

from __future__ import annotations
import sys
from pathlib import Path

import pandas as pd
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from src import config as cfg

ROOT  = Path(__file__).parent
GPD   = cfg.DIRS["gates"] / "gpd_marginal_params.parquet"
OUT   = ROOT / "paper" / "tables" / "tabA2_gpd_params.tex"
OUT.parent.mkdir(parents=True, exist_ok=True)

gpd = pd.read_parquet(GPD)

n_total    = len(gpd)
n_pass     = gpd["gate2_pass"].sum()
n_fail     = n_total - n_pass

passed = gpd[gpd["gate2_pass"] == True]
failed = gpd[gpd["gate2_pass"] == False]

# Summary statistics for passed
xi_med  = passed["xi"].median()
xi_q25  = passed["xi"].quantile(0.25)
xi_q75  = passed["xi"].quantile(0.75)
u_med   = passed["threshold_quantile"].median()
u_q25   = passed["threshold_quantile"].quantile(0.25)
u_q75   = passed["threshold_quantile"].quantile(0.75)
n_exc   = passed["n_exceed_declustered"].median()
theta   = passed["theta_hat"].median()

rows = [
    ("\\multicolumn{3}{@{}l}{\\textit{Gate G2 overview}} \\\\", "", ""),
    ("Total series (station $\\times$ direction)",  f"{n_total}",  ""),
    ("Passed Gate G2",  f"{n_pass} ({n_pass/n_total:.1%})", ""),
    ("Failed (low series)",  f"{n_fail}",
     "5 up-direction low-activity"),
    ("\\multicolumn{3}{@{}l}{\\textit{Passed series — summary statistics}} \\\\", "", ""),
    ("Threshold quantile $u$",
     f"{u_med:.2f}",
     f"[IQR {u_q25:.2f}--{u_q75:.2f}]"),
    ("Shape $\\hat{\\xi}$ (GPD)",
     f"{xi_med:.3f}",
     f"[IQR {xi_q25:.3f}--{xi_q75:.3f}]"),
    ("Median declustered exceedances",
     f"{n_exc:.0f}", "per series"),
    ("Median extremal index $\\hat{\\theta}$",
     f"{theta:.3f}", "Ferro--Segers"),
]

lines = []
lines.append("% Auto-generated by P_tabA2_gpd_params.py — do not edit manually")
lines.append("\\begin{tabular}{@{}lll@{}}")
lines.append("\\toprule")
lines.append("Statistic & Value & Note \\\\")
lines.append("\\midrule")
for lab, val, note in rows:
    if "multicolumn" in lab:
        lines.append(f"{lab} \\\\")
        lines.append("\\midrule")
    else:
        lines.append(f"{lab} & {val} & {note} \\\\")
lines.append("\\botrule")
lines.append("\\end{tabular}")

OUT.write_text("\n".join(lines))
print(f"[OK] Tab A.2 saved → {OUT}")
print(f"  n_total={n_total}, n_pass={n_pass}, xi_med={xi_med:.3f}, u_med={u_med:.2f}")
